CREATE TABLE "REQUEST_POOL"
(
    "SERVICE_NAME"  VARCHAR2(50),
    "SERVICE_URL"   VARCHAR2(250) NOT NULL ENABLE,
    "PARAMS"        VARCHAR2(50),
    "FINISHED_DATE" DATE,
    "CREATED_DATE"  DATE DEFAULT CURRENT_DATE NOT NULL ENABLE,
    "STATUS"        VARCHAR2(50) DEFAULT 'WAITING'
)